using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class UnionMethods
{
    public static string Render(GirModel.Union union)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(union.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(union as GirModel.PlatformDependent)}
public partial class {union.Name}
{{
    {union.Functions
        .Select(FunctionRenderer.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
