using Generator.Model;

namespace Generator.Renderer.Public;

internal static class UnionFramework
{
    public static string Render(GirModel.Union union)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(union.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(union as GirModel.PlatformDependent)}
public partial class {union.Name} : GLib.BoxedRecord, GObject.GTypeProvider, GObject.InstanceFactory
{{
    public IntPtr Handle {{ get; }}

    public {union.Name}(IntPtr handle)
    {{
        Handle = handle;
    }}

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {{
        return new {union.Name}(handle);
    }}

    public static GObject.Type GetGType()
    {{
        return {Namespace.GetInternalName(union.Namespace)}.{union.Name}.GetGType();
    }}

    System.IntPtr GLib.BoxedRecord.GetHandle()
    {{
        return Handle;
    }}
}}";
    }
}
