// Generated by Tmds.DBus.Tool v0.92.0 with arguments: codegen --bus session --service org.gnome.SessionManager --protocol-api --namespace GirCoreSession.DBus --output SessionManager.cs
// <auto-generated/>
#nullable enable
namespace GirCoreSession.DBus
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Tmds.DBus.Protocol;
    interface ISessionManagerProperties
    {
        string? SessionName { get; }
        string? Renderer { get; }
        bool? SessionIsActive { get; }
        uint? InhibitedActions { get; }
        bool? RestoreSupported { get; }
        bool HasSessionNameChanged { get; }
        bool HasRendererChanged { get; }
        bool HasSessionIsActiveChanged { get; }
        bool HasInhibitedActionsChanged { get; }
        bool HasRestoreSupportedChanged { get; }
        bool AreAllPropertiesSet();
        SessionManagerProperties EnsureAllPropertiesSet();
    }
    sealed class SessionManagerProperties : ISessionManagerProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x1FU; // 5 properties
        private static uint Flag(SessionManagerProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public SessionManagerProperties() { }
#nullable disable
        [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private SessionManagerProperties(bool _) { }
#nullable enable
        private void EnsureSet(SessionManagerProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new InvalidOperationException("Property is not set.");
            }
        }
        private string _sessionName = default!;
        public required string SessionName
        {
            get { EnsureSet(SessionManagerProperty.SessionName); return _sessionName; }
            set { _sessionName = value; __set |= Flag(SessionManagerProperty.SessionName); }
        }
        private string _renderer = default!;
        public required string Renderer
        {
            get { EnsureSet(SessionManagerProperty.Renderer); return _renderer; }
            set { _renderer = value; __set |= Flag(SessionManagerProperty.Renderer); }
        }
        private bool _sessionIsActive = default!;
        public required bool SessionIsActive
        {
            get { EnsureSet(SessionManagerProperty.SessionIsActive); return _sessionIsActive; }
            set { _sessionIsActive = value; __set |= Flag(SessionManagerProperty.SessionIsActive); }
        }
        private uint _inhibitedActions = default!;
        public required uint InhibitedActions
        {
            get { EnsureSet(SessionManagerProperty.InhibitedActions); return _inhibitedActions; }
            set { _inhibitedActions = value; __set |= Flag(SessionManagerProperty.InhibitedActions); }
        }
        private bool _restoreSupported = default!;
        public required bool RestoreSupported
        {
            get { EnsureSet(SessionManagerProperty.RestoreSupported); return _restoreSupported; }
            set { _restoreSupported = value; __set |= Flag(SessionManagerProperty.RestoreSupported); }
        }
        string? ISessionManagerProperties.SessionName
            => IsSet(SessionManagerProperty.SessionName) ? _sessionName : default(string?);
        string? ISessionManagerProperties.Renderer
            => IsSet(SessionManagerProperty.Renderer) ? _renderer : default(string?);
        bool? ISessionManagerProperties.SessionIsActive
            => IsSet(SessionManagerProperty.SessionIsActive) ? _sessionIsActive : default(bool?);
        uint? ISessionManagerProperties.InhibitedActions
            => IsSet(SessionManagerProperty.InhibitedActions) ? _inhibitedActions : default(uint?);
        bool? ISessionManagerProperties.RestoreSupported
            => IsSet(SessionManagerProperty.RestoreSupported) ? _restoreSupported : default(bool?);
        bool ISessionManagerProperties.HasSessionNameChanged
            => IsSet(SessionManagerProperty.SessionName) || IsInvalidated(SessionManagerProperty.SessionName);
        bool ISessionManagerProperties.HasRendererChanged
            => IsSet(SessionManagerProperty.Renderer) || IsInvalidated(SessionManagerProperty.Renderer);
        bool ISessionManagerProperties.HasSessionIsActiveChanged
            => IsSet(SessionManagerProperty.SessionIsActive) || IsInvalidated(SessionManagerProperty.SessionIsActive);
        bool ISessionManagerProperties.HasInhibitedActionsChanged
            => IsSet(SessionManagerProperty.InhibitedActions) || IsInvalidated(SessionManagerProperty.InhibitedActions);
        bool ISessionManagerProperties.HasRestoreSupportedChanged
            => IsSet(SessionManagerProperty.RestoreSupported) || IsInvalidated(SessionManagerProperty.RestoreSupported);
        SessionManagerProperties ISessionManagerProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static SessionManagerProperties CreateUninitialized() => new SessionManagerProperties(false);
        private bool HasFlag(uint flags, SessionManagerProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static SessionManagerProperty ParsePropertyName(string propertyName)
        {
            return propertyName switch
            {
                "SessionName" => SessionManagerProperty.SessionName,
                "Renderer" => SessionManagerProperty.Renderer,
                "SessionIsActive" => SessionManagerProperty.SessionIsActive,
                "InhibitedActions" => SessionManagerProperty.InhibitedActions,
                "RestoreSupported" => SessionManagerProperty.RestoreSupported,
                _ => 0
            };
        }
        private bool IsSet(SessionManagerProperty property) => HasFlag(__set, property);
        private bool IsInvalidated(SessionManagerProperty property) => HasFlag(__invalidated, property);
        private void SetInvalidated(SessionManagerProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void SetInvalidated(string propertyName) => SetInvalidated(ParsePropertyName(propertyName));
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static ISessionManagerProperties ReadFrom(ref Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            ArrayEnd arrayEnd = reader.ReadArrayStart(DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "SessionName":
                        reader.ReadSignature("s"u8);
                        props.SessionName = reader.ReadString();
                        break;
                    case "Renderer":
                        reader.ReadSignature("s"u8);
                        props.Renderer = reader.ReadString();
                        break;
                    case "SessionIsActive":
                        reader.ReadSignature("b"u8);
                        props.SessionIsActive = reader.ReadBool();
                        break;
                    case "InhibitedActions":
                        reader.ReadSignature("u"u8);
                        props.InhibitedActions = reader.ReadUInt32();
                        break;
                    case "RestoreSupported":
                        reader.ReadSignature("b"u8);
                        props.RestoreSupported = reader.ReadBool();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                ArrayEnd invalidatedEnd = reader.ReadArrayStart(DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "SessionName" => Flag(SessionManagerProperty.SessionName),
                        "Renderer" => Flag(SessionManagerProperty.Renderer),
                        "SessionIsActive" => Flag(SessionManagerProperty.SessionIsActive),
                        "InhibitedActions" => Flag(SessionManagerProperty.InhibitedActions),
                        "RestoreSupported" => Flag(SessionManagerProperty.RestoreSupported),
                        _ => 0
                    };
                }
            }
            return props;
        }
        private enum SessionManagerProperty
        {
            UnknownProperty = 0,
            SessionName = 1,
            Renderer = 2,
            SessionIsActive = 3,
            InhibitedActions = 4,
            RestoreSupported = 5
        }
    }
    sealed partial class SessionManager : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.gnome.SessionManager";
        public SessionManager(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task SetenvAsync(string variable, string value)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "Setenv");
                writer.WriteString(variable);
                writer.WriteString(value);
                return writer.CreateMessage();
            }
        }
        public Task<string> GetLocaleAsync(int category)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_s(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "i",
                    member: "GetLocale");
                writer.WriteInt32(category);
                return writer.CreateMessage();
            }
        }
        public Task InitializationErrorAsync(string message, bool fatal)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "sb",
                    member: "InitializationError");
                writer.WriteString(message);
                writer.WriteBool(fatal);
                return writer.CreateMessage();
            }
        }
        public Task InitializedAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Initialized");
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> RegisterClientAsync(string appId, string ignored)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "RegisterClient");
                writer.WriteString(appId);
                writer.WriteString(ignored);
                return writer.CreateMessage();
            }
        }
        public Task UnregisterClientAsync(ObjectPath clientId)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "o",
                    member: "UnregisterClient");
                writer.WriteObjectPath(clientId);
                return writer.CreateMessage();
            }
        }
        public Task<(uint Reason, string InstanceId, string[] CleanupIds)> RegisterRestoreAsync(string appId, string dbusName)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_usas(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "RegisterRestore");
                writer.WriteString(appId);
                writer.WriteString(dbusName);
                return writer.CreateMessage();
            }
        }
        public Task DeletedInstanceIdsAsync(string appId, string[] ids)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "sas",
                    member: "DeletedInstanceIds");
                writer.WriteString(appId);
                writer.WriteArray(ids);
                return writer.CreateMessage();
            }
        }
        public Task UnregisterRestoreAsync(string appId, string instanceId)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "UnregisterRestore");
                writer.WriteString(appId);
                writer.WriteString(instanceId);
                return writer.CreateMessage();
            }
        }
        public Task<uint> InhibitAsync(string appId, uint ignored, string reason, uint flags)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_u(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "susu",
                    member: "Inhibit");
                writer.WriteString(appId);
                writer.WriteUInt32(ignored);
                writer.WriteString(reason);
                writer.WriteUInt32(flags);
                return writer.CreateMessage();
            }
        }
        public Task UninhibitAsync(uint inhibitCookie)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "u",
                    member: "Uninhibit");
                writer.WriteUInt32(inhibitCookie);
                return writer.CreateMessage();
            }
        }
        public Task<bool> IsInhibitedAsync(uint flags)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_b(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "u",
                    member: "IsInhibited");
                writer.WriteUInt32(flags);
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath[]> GetInhibitorsAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_ao(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetInhibitors");
                return writer.CreateMessage();
            }
        }
        public Task ShutdownAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Shutdown");
                return writer.CreateMessage();
            }
        }
        public Task RebootAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Reboot");
                return writer.CreateMessage();
            }
        }
        public Task SuspendAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Suspend");
                return writer.CreateMessage();
            }
        }
        public Task<uint> CanShutdownAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_u(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "CanShutdown");
                return writer.CreateMessage();
            }
        }
        public Task<uint> CanRebootAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_u(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "CanReboot");
                return writer.CreateMessage();
            }
        }
        public Task<uint> CanSuspendAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_u(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "CanSuspend");
                return writer.CreateMessage();
            }
        }
        public Task SetRebootToFirmwareSetupAsync(bool enable)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "b",
                    member: "SetRebootToFirmwareSetup");
                writer.WriteBool(enable);
                return writer.CreateMessage();
            }
        }
        public Task<bool> CanRebootToFirmwareSetupAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_b(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "CanRebootToFirmwareSetup");
                return writer.CreateMessage();
            }
        }
        public Task LogoutAsync(uint mode)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "u",
                    member: "Logout");
                writer.WriteUInt32(mode);
                return writer.CreateMessage();
            }
        }
        public Task<bool> IsSessionRunningAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_b(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "IsSessionRunning");
                return writer.CreateMessage();
            }
        }
        public ValueTask<IDisposable> WatchClientAddedAsync(Action<Exception?, ObjectPath> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "ClientAdded", (Message m, object? s) => MessageReader.Read_o(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchClientRemovedAsync(Action<Exception?, ObjectPath> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "ClientRemoved", (Message m, object? s) => MessageReader.Read_o(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchInhibitorAddedAsync(Action<Exception?, ObjectPath> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "InhibitorAdded", (Message m, object? s) => MessageReader.Read_o(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchInhibitorRemovedAsync(Action<Exception?, ObjectPath> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "InhibitorRemoved", (Message m, object? s) => MessageReader.Read_o(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchSessionRunningAsync(Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "SessionRunning", handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchSessionOverAsync(Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "SessionOver", handler, this, emitOnCapturedContext, flags);
        public Task<string> GetSessionNameAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("SessionName"), (Message m, object? s) => MessageReader.Read_v_s(m), this);
        public Task<string> GetRendererAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Renderer"), (Message m, object? s) => MessageReader.Read_v_s(m), this);
        public Task<bool> GetSessionIsActiveAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("SessionIsActive"), (Message m, object? s) => MessageReader.Read_v_b(m), this);
        public Task<uint> GetInhibitedActionsAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("InhibitedActions"), (Message m, object? s) => MessageReader.Read_v_u(m), this);
        public Task<bool> GetRestoreSupportedAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("RestoreSupported"), (Message m, object? s) => MessageReader.Read_v_b(m), this);
        public async Task<ISessionManagerProperties> GetPropertiesAsync()
        {
            var props = await Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (Message m, object? s) => ReadMessage(m), this).ConfigureAwait(false);
            props.EnsureAllPropertiesSet();
            return props;
            static ISessionManagerProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                return SessionManagerProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public ValueTask<IDisposable> WatchPropertiesChangedAsync(Action<Exception?, ISessionManagerProperties> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (Message m, object? s) => ReadMessage(m), handler, this, emitOnCapturedContext, flags);
            static ISessionManagerProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return SessionManagerProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    sealed partial class ClientPrivate : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.gnome.SessionManager.ClientPrivate";
        public ClientPrivate(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task EndSessionResponseAsync(bool isOk, string reason)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "bs",
                    member: "EndSessionResponse");
                writer.WriteBool(isOk);
                writer.WriteString(reason);
                return writer.CreateMessage();
            }
        }
        public ValueTask<IDisposable> WatchStopAsync(Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "Stop", handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchQueryEndSessionAsync(Action<Exception?, uint> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "QueryEndSession", (Message m, object? s) => MessageReader.Read_u(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchEndSessionAsync(Action<Exception?, uint> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "EndSession", (Message m, object? s) => MessageReader.Read_u(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchCancelEndSessionAsync(Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "CancelEndSession", handler, this, emitOnCapturedContext, flags);
    }
    sealed partial class Inhibitor : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.gnome.SessionManager.Inhibitor";
        public Inhibitor(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task<string> GetAppIdAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_s(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetAppId");
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> GetClientIdAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetClientId");
                return writer.CreateMessage();
            }
        }
        public Task<string> GetReasonAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_s(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetReason");
                return writer.CreateMessage();
            }
        }
        public Task<uint> GetFlagsAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_u(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetFlags");
                return writer.CreateMessage();
            }
        }
    }
    interface IPresenceProperties
    {
        uint? Status { get; }
        string? StatusText { get; }
        bool HasStatusChanged { get; }
        bool HasStatusTextChanged { get; }
        bool AreAllPropertiesSet();
        PresenceProperties EnsureAllPropertiesSet();
    }
    sealed class PresenceProperties : IPresenceProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x3U; // 2 properties
        private static uint Flag(PresenceProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public PresenceProperties() { }
#nullable disable
        [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private PresenceProperties(bool _) { }
#nullable enable
        private void EnsureSet(PresenceProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new InvalidOperationException("Property is not set.");
            }
        }
        private uint _status = default!;
        public required uint Status
        {
            get { EnsureSet(PresenceProperty.Status); return _status; }
            set { _status = value; __set |= Flag(PresenceProperty.Status); }
        }
        private string _statusText = default!;
        public required string StatusText
        {
            get { EnsureSet(PresenceProperty.StatusText); return _statusText; }
            set { _statusText = value; __set |= Flag(PresenceProperty.StatusText); }
        }
        uint? IPresenceProperties.Status
            => IsSet(PresenceProperty.Status) ? _status : default(uint?);
        string? IPresenceProperties.StatusText
            => IsSet(PresenceProperty.StatusText) ? _statusText : default(string?);
        bool IPresenceProperties.HasStatusChanged
            => IsSet(PresenceProperty.Status) || IsInvalidated(PresenceProperty.Status);
        bool IPresenceProperties.HasStatusTextChanged
            => IsSet(PresenceProperty.StatusText) || IsInvalidated(PresenceProperty.StatusText);
        PresenceProperties IPresenceProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static PresenceProperties CreateUninitialized() => new PresenceProperties(false);
        private bool HasFlag(uint flags, PresenceProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static PresenceProperty ParsePropertyName(string propertyName)
        {
            return propertyName switch
            {
                "status" => PresenceProperty.Status,
                "status-text" => PresenceProperty.StatusText,
                _ => 0
            };
        }
        private bool IsSet(PresenceProperty property) => HasFlag(__set, property);
        private bool IsInvalidated(PresenceProperty property) => HasFlag(__invalidated, property);
        private void SetInvalidated(PresenceProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void SetInvalidated(string propertyName) => SetInvalidated(ParsePropertyName(propertyName));
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static IPresenceProperties ReadFrom(ref Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            ArrayEnd arrayEnd = reader.ReadArrayStart(DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "status":
                        reader.ReadSignature("u"u8);
                        props.Status = reader.ReadUInt32();
                        break;
                    case "status-text":
                        reader.ReadSignature("s"u8);
                        props.StatusText = reader.ReadString();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                ArrayEnd invalidatedEnd = reader.ReadArrayStart(DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "status" => Flag(PresenceProperty.Status),
                        "status-text" => Flag(PresenceProperty.StatusText),
                        _ => 0
                    };
                }
            }
            return props;
        }
        private enum PresenceProperty
        {
            UnknownProperty = 0,
            Status = 1,
            StatusText = 2
        }
    }
    sealed partial class Presence : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.gnome.SessionManager.Presence";
        public Presence(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task SetStatusAsync(uint status)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "u",
                    member: "SetStatus");
                writer.WriteUInt32(status);
                return writer.CreateMessage();
            }
        }
        public Task SetStatusTextAsync(string statusText)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "s",
                    member: "SetStatusText");
                writer.WriteString(statusText);
                return writer.CreateMessage();
            }
        }
        public ValueTask<IDisposable> WatchStatusChangedAsync(Action<Exception?, uint> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "StatusChanged", (Message m, object? s) => MessageReader.Read_u(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchStatusTextChangedAsync(Action<Exception?, string> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "StatusTextChanged", (Message m, object? s) => MessageReader.Read_s(m), handler, this, emitOnCapturedContext, flags);
        public Task SetStatusPropertyAsync(uint value)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: "org.freedesktop.DBus.Properties",
                    signature: "ssv",
                    member: "Set");
                writer.WriteString(DBusInterfaceName);
                writer.WriteString("status");
                writer.WriteSignature("u");
                writer.WriteUInt32(value);
                return writer.CreateMessage();
            }
        }
        public Task SetStatusTextPropertyAsync(string value)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: "org.freedesktop.DBus.Properties",
                    signature: "ssv",
                    member: "Set");
                writer.WriteString(DBusInterfaceName);
                writer.WriteString("status-text");
                writer.WriteSignature("s");
                writer.WriteString(value);
                return writer.CreateMessage();
            }
        }
        public Task<uint> GetStatusAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("status"), (Message m, object? s) => MessageReader.Read_v_u(m), this);
        public Task<string> GetStatusTextAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("status-text"), (Message m, object? s) => MessageReader.Read_v_s(m), this);
        public async Task<IPresenceProperties> GetPropertiesAsync()
        {
            var props = await Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (Message m, object? s) => ReadMessage(m), this).ConfigureAwait(false);
            props.EnsureAllPropertiesSet();
            return props;
            static IPresenceProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                return PresenceProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public ValueTask<IDisposable> WatchPropertiesChangedAsync(Action<Exception?, IPresenceProperties> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (Message m, object? s) => ReadMessage(m), handler, this, emitOnCapturedContext, flags);
            static IPresenceProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return PresenceProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    static partial class ObjectFactory
    {
        public static SessionManager CreateSessionManager(this DBusService service, ObjectPath path) => new SessionManager(service.Connection, service.Name, path);
        public static ClientPrivate CreateClientPrivate(this DBusService service, ObjectPath path) => new ClientPrivate(service.Connection, service.Name, path);
        public static Inhibitor CreateInhibitor(this DBusService service, ObjectPath path) => new Inhibitor(service.Connection, service.Name, path);
        public static Presence CreatePresence(this DBusService service, ObjectPath path) => new Presence(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static string Read_s(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadString();
        }
        public static ObjectPath Read_o(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadObjectPath();
        }
        public static (uint, string, string[]) Read_usas(Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadUInt32();
            var arg1 = reader.ReadString();
            var arg2 = reader.ReadArrayOfString();
            return (arg0, arg1, arg2);
        }
        public static uint Read_u(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadUInt32();
        }
        public static bool Read_b(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadBool();
        }
        public static ObjectPath[] Read_ao(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadArrayOfObjectPath();
        }
        public static string Read_v_s(Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("s"u8);
            return reader.ReadString();
        }
        public static bool Read_v_b(Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("b"u8);
            return reader.ReadBool();
        }
        public static uint Read_v_u(Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("u"u8);
            return reader.ReadUInt32();
        }
    }
    file static class MessageWriterExtensions
    {
    }
}
