// Generated by Tmds.DBus.Tool v0.92.0 with arguments: codegen systemd-minimal.xml --protocol-api --namespace GirCoreSession.DBus --output Systemd.cs
// <auto-generated/>
#nullable enable
namespace GirCoreSession.DBus
{
    using System;
    using Tmds.DBus.Protocol;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    sealed partial class Manager : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.systemd1.Manager";
        public Manager(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task<ObjectPath> StartUnitAsync(string name, string mode)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "StartUnit");
                writer.WriteString(name);
                writer.WriteString(mode);
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> StopUnitAsync(string name, string mode)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "StopUnit");
                writer.WriteString(name);
                writer.WriteString(mode);
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> RestartUnitAsync(string name, string mode)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ss",
                    member: "RestartUnit");
                writer.WriteString(name);
                writer.WriteString(mode);
                return writer.CreateMessage();
            }
        }
        public Task ResetFailedUnitAsync(string name)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "s",
                    member: "ResetFailedUnit");
                writer.WriteString(name);
                return writer.CreateMessage();
            }
        }
        public Task ResetFailedAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "ResetFailed");
                return writer.CreateMessage();
            }
        }
        public Task SetEnvironmentAsync(string[] assignments)
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "as",
                    member: "SetEnvironment");
                writer.WriteArray(assignments);
                return writer.CreateMessage();
            }
        }
        public Task PowerOffAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "PowerOff");
                return writer.CreateMessage();
            }
        }
        public Task RebootAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Reboot");
                return writer.CreateMessage();
            }
        }
        public Task SuspendAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Suspend");
                return writer.CreateMessage();
            }
        }
        public ValueTask<IDisposable> WatchUnitNewAsync(Action<Exception?, (string Id, ObjectPath Unit)> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "UnitNew", (Message m, object? s) => MessageReader.Read_so(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchUnitRemovedAsync(Action<Exception?, (string Id, ObjectPath Unit)> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "UnitRemoved", (Message m, object? s) => MessageReader.Read_so(m), handler, this, emitOnCapturedContext, flags);
        public ValueTask<IDisposable> WatchJobRemovedAsync(Action<Exception?, (uint Id, ObjectPath Job, string Unit, string Result)> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "JobRemoved", (Message m, object? s) => MessageReader.Read_uoss(m), handler, this, emitOnCapturedContext, flags);
    }
    static partial class ObjectFactory
    {
        public static Manager CreateManager(this DBusService service, ObjectPath path) => new Manager(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static ObjectPath Read_o(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadObjectPath();
        }
        public static (string, ObjectPath) Read_so(Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadString();
            var arg1 = reader.ReadObjectPath();
            return (arg0, arg1);
        }
        public static (uint, ObjectPath, string, string) Read_uoss(Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadUInt32();
            var arg1 = reader.ReadObjectPath();
            var arg2 = reader.ReadString();
            var arg3 = reader.ReadString();
            return (arg0, arg1, arg2, arg3);
        }
    }
    file static class MessageWriterExtensions
    {
    }
}
