[Unit]
Description=GirCore Shell (overriding GNOME Shell)

[Service]
Type=notify
Environment=XDG_SESSION_TYPE=wayland
Environment=XDG_SESSION_CLASS=user
Environment=XDG_CURRENT_DESKTOP=GNOME
Environment=XDG_DESKTOP_SESSION=gnome
Environment=DESKTOP_SESSION=gnome
Environment=MUTTER_DEBUG_DISABLE_HW_CURSORS=1
Environment=MUTTER_DEBUG_FORCE_KMS_MODE=simple
ExecStart=
ExecStart=/usr/bin/gircore-shell shell:mode=%i
